/********************************************************************
* /home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/UserDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/UserDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableUserDict();
extern void G__cpp_setup_inheritanceUserDict();
extern void G__cpp_setup_typetableUserDict();
extern void G__cpp_setup_memvarUserDict();
extern void G__cpp_setup_globalUserDict();
extern void G__cpp_setup_memfuncUserDict();
extern void G__cpp_setup_funcUserDict();
extern void G__set_cpp_environmentUserDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2CalArray.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2Calorimeter.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2CB.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2Compton.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2CosmicCal.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2CrystalBall.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2CylMWPC.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2CylStripSven.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2CylWireSven.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2Efficiency.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2Event.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2FPMicro.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2GenericApp.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2PhotoPhysics.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2PlasticPID.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2SpinPolPhysics.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2TAPS2008.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2TAPS2009.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2Taps2009LE.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2TAPS_BaF2.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2Taps.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2TAPS.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2TAPS_PbWO4.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2TAPS_Veto.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2ThreshPi0.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2UserAnalysis.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2UserControl.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2UserPhysics.h"
#include "/home/dpaudyal/research/AcquRoot/4v6/2012.09.31/acqu/root/src/TA2WCLayerSven.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__UserDictLN_TClass;
extern G__linked_taginfo G__UserDictLN_TBuffer;
extern G__linked_taginfo G__UserDictLN_TMemberInspector;
extern G__linked_taginfo G__UserDictLN_TObject;
extern G__linked_taginfo G__UserDictLN_TNamed;
extern G__linked_taginfo G__UserDictLN_TString;
extern G__linked_taginfo G__UserDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__UserDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__UserDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__UserDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__UserDictLN_TVector3;
extern G__linked_taginfo G__UserDictLN_TA2ClusterDetector;
extern G__linked_taginfo G__UserDictLN_HitCluster_t;
extern G__linked_taginfo G__UserDictLN_TA2CalArray;
extern G__linked_taginfo G__UserDictLN_HitClusterUCLA_t;
extern G__linked_taginfo G__UserDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__UserDictLN_TFile;
extern G__linked_taginfo G__UserDictLN_TTree;
extern G__linked_taginfo G__UserDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__UserDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_TQObject;
extern G__linked_taginfo G__UserDictLN_TApplication;
extern G__linked_taginfo G__UserDictLN_TA2System;
extern G__linked_taginfo G__UserDictLN_TA2Analysis;
extern G__linked_taginfo G__UserDictLN_TAcquRoot;
extern G__linked_taginfo G__UserDictLN_TH1F;
extern G__linked_taginfo G__UserDictLN_TF1;
extern G__linked_taginfo G__UserDictLN_TCutG;
extern G__linked_taginfo G__UserDictLN_TA2DataManager;
extern G__linked_taginfo G__UserDictLN_TH2F;
extern G__linked_taginfo G__UserDictLN_TA2HistManager;
extern G__linked_taginfo G__UserDictLN_TA2Detector;
extern G__linked_taginfo G__UserDictLN_HitD2A_t;
extern G__linked_taginfo G__UserDictLN_TLorentzVector;
extern G__linked_taginfo G__UserDictLN_TA2Particle;
extern G__linked_taginfo G__UserDictLN_TA2Apparatus;
extern G__linked_taginfo G__UserDictLN_TA2Calorimeter;
extern G__linked_taginfo G__UserDictLN_TRandom3;
extern G__linked_taginfo G__UserDictLN_TA2WCLayer;
extern G__linked_taginfo G__UserDictLN_TA2WireChamber;
extern G__linked_taginfo G__UserDictLN_TA2WCLayerSven;
extern G__linked_taginfo G__UserDictLN_TA2CylStripSven;
extern G__linked_taginfo G__UserDictLN_TA2CylWireSven;
extern G__linked_taginfo G__UserDictLN_TA2Physics;
extern G__linked_taginfo G__UserDictLN_TA2CylMWPC;
extern G__linked_taginfo G__UserDictLN_TA2CrystalBall;
extern G__linked_taginfo G__UserDictLN_TA2PlasticPID;
extern G__linked_taginfo G__UserDictLN_TA2CB;
extern G__linked_taginfo G__UserDictLN_TA2Ladder;
extern G__linked_taginfo G__UserDictLN_TA2Tagger;
extern G__linked_taginfo G__UserDictLN_TA2TAPS_BaF2;
extern G__linked_taginfo G__UserDictLN_TNtuple;
extern G__linked_taginfo G__UserDictLN_TA2TAPS2009;
extern G__linked_taginfo G__UserDictLN_TA2PhotoPhysics;
extern G__linked_taginfo G__UserDictLN_TA2Compton;
extern G__linked_taginfo G__UserDictLN_TA2GenericDetector;
extern G__linked_taginfo G__UserDictLN_TA2LongScint;
extern G__linked_taginfo G__UserDictLN_TA2CosmicCal;
extern G__linked_taginfo G__UserDictLN_TA2Efficiency;
extern G__linked_taginfo G__UserDictLN_TA2Event;
extern G__linked_taginfo G__UserDictLN_TA2FPMicro;
extern G__linked_taginfo G__UserDictLN_TA2GenericApp;
extern G__linked_taginfo G__UserDictLN_TA2TAPS_Veto;
extern G__linked_taginfo G__UserDictLN_TA2Taps;
extern G__linked_taginfo G__UserDictLN_TA2SpinPolPhysics;
extern G__linked_taginfo G__UserDictLN_TA2TAPS_PbWO4;
extern G__linked_taginfo G__UserDictLN_TA2TAPS2008;
extern G__linked_taginfo G__UserDictLN_TA2Taps2009LE;
extern G__linked_taginfo G__UserDictLN_TA2TAPS;
extern G__linked_taginfo G__UserDictLN_TA2ThreshPi0;
extern G__linked_taginfo G__UserDictLN_TA2UserAnalysis;
extern G__linked_taginfo G__UserDictLN_TRint;
extern G__linked_taginfo G__UserDictLN_TA2Control;
extern G__linked_taginfo G__UserDictLN_TA2UserControl;
extern G__linked_taginfo G__UserDictLN_TA2UserPhysics;

/* STUB derived class for protected member access */
